import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Link from 'next/link'
import Image from 'next/image'
import logo from '../public/logo.png'

export const metadata: Metadata = {
  title: "Solar Triangle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Darker Grotesque' rel='stylesheet'></link>
      </head>
      <body>
        <header>
          <div className="flex justify-between items-center mx-5 my-2">
            <Image
              src={logo}
              alt="logo"
              width={120}
              height={65}
            />
            <Link
              href={"/"}
              className="font-[Darker_Grotesque] text-lg">
              Account
            </Link>
          </div>
        </header>
        <div className="flex flex-col min-h-screen my-8">
          <Navbar />
          <main className="flex-1 flex">
            {children}
          </main>
          <footer className="flex justify-center">
            <h4>Copyright</h4>
          </footer>
        </div>
      </body>
    </html>
  );
}
