import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link'
import Image from 'next/image'
import logo from '../public/logo.png'
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Solar Triangle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300..900&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Lexend+Deca:wght@100..900&family=Saira:ital,wght@0,100..900;1,100..900&family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet"></link>
      </head>
      <body className="flex flex-col max-w-6xl min-h-screen mx-auto">
        <header className="flex justify-between items-center mx-5 my-2">
          <Image
            src={logo}
            alt="logo"
            width={120}
            height={65}
          />
          <Link
            href={"/login"}
            className="font-[Darker_Grotesque] text-lg">
            Account
          </Link>
        </header>
        <main className="flex-1">
          <Navbar />
          {children}
        </main>
        <footer className="flex justify-center font-[Inter] font-light">
          <h4 className="pb-2 text-sm">Copyright @DayDream</h4>
        </footer>
      </body>
    </html>
  );
}
